server:
  port: 8888

database:
  host: "mongodb.navexplorer.com"
  name: "testnet-v2"

communityFund:
  blocksInCycle: 180
  minQuorum: 0.5
  proposalVoting:
    cycles: 4
    accept: 0.7
    reject: 0.7
  paymentVoting:
    cycles: 4
    accept: 0.7
    reject: 0.7