debug: true

ssl: false

server:
  port: 8080

Network: mainnet

elasticSearch:
  urls: http://localhost:9200
  sniff: false
  healthCheck: true

communityFund:
  blocksInCycle: 20160
  minQuorum: 0.5
  proposalVoting:
    cycles: 4
    accept: 0.7
    reject: 0.7
  paymentVoting:
    cycles: 4
    accept: 0.7
    reject: 0.7

softFork:
  blocksInCycle: 20160
  accept: 0.75
